import { Headers } from './types.js';
import {
  AlertsClient,
  AlertItemsClient,
  AssetsClient,
  AttributesClient,
  CommunicationClient,
  ComponentCommandsClient,
  ComponentObjectsClient,
  RoutineObjectsClient,
  ComponentsClient,
  DashboardChartItemsClient,
  DashboardChartsClient,
  DashboardGraphEdgesClient,
  DashboardGraphNodesClient,
  DashboardGraphsClient,
  DashboardGraphsEdgesBulkClient,
  DashboardGraphsNodesBulkClient,
  DashboardsClient,
  DashboardTabsClient,
  DatalakeDataClient,
  DeploymentsClient,
  FilesClient,
  QueriesClient,
  SecretsClient,
} from './engine/index.js';

export const Engine = (headers: Headers) => {
  return {
    alerts: AlertsClient(headers),
    assets: AssetsClient(headers),
    attributes: AttributesClient(headers),
    components: ComponentsClient(headers),
    files: FilesClient(headers),
    queries: QueriesClient(headers),
    communication: CommunicationClient(headers),
    componentObjects: ComponentObjectsClient(headers),
    routineObjects: RoutineObjectsClient(headers),
    componentCommands: ComponentCommandsClient(headers),
    dashboards: DashboardsClient(headers),
    dashboardTabs: DashboardTabsClient(headers),
    dashboardCharts: DashboardChartsClient(headers),
    dashboardChartItems: DashboardChartItemsClient(headers),
    graphsClient: DashboardGraphsClient(headers),
    graphNodesClient: DashboardGraphNodesClient(headers),
    graphNodesBulkClient: DashboardGraphsNodesBulkClient(headers),
    graphEdgesClient: DashboardGraphEdgesClient(headers),
    graphEdgesBulkClient: DashboardGraphsEdgesBulkClient(headers),
    secrets: SecretsClient(headers),
    deployments: DeploymentsClient(headers),
    datalakeData: DatalakeDataClient(headers),
  };
};
