name: Pre Release
on:
  pull_request:
    types:
      [opened, synchronize]
    branches:
      - master


jobs:
  verify_version:
    runs-on: ubuntu-latest
    name: Verify version is a valid release version and is higher than last PyPi package and master version
    steps:
      # get master version
      - name: Checkout to master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Get version from master branch
        run: echo "MASTER_VERSION=$(grep -E 'version' package.json | awk '{print $3}' | tr -d '\"\,')" >> "$GITHUB_ENV"

      # get current branch version
      - name: Checkout to feature branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Get version from feature branch
        run: echo "CURRENT_VERSION=$(grep -E 'version' package.json | awk '{print $3}' | tr -d '\"\,')" >> "$GITHUB_ENV"

      - name: Verify version is greater than master version
        run: python .github/workflows/scripts/check_master_version.py ${{ env.MASTER_VERSION }} ${{ env.CURRENT_VERSION }}
