#TODO: Refactor to use npm instead of pnpm
name: Publish
on:
  push:
    branches:
      - master
      - hotfix/* # I'm not enablin this for master yet, because I need the env vars to be set up in deployment for this to work.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"
      - run: npm ci && npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
