name: snyk report
on:
  workflow_run:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  make-snyk-report:
    runs-on: ubuntu-latest
    name: Create vulnerabilities report using Snyk
    steps:
      - uses: actions/checkout@v3
      - name: Install Snyk
        run: npm install snyk -g
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_API_KEY }}
      - name: Create Snyk report
        run: |
          mkdir .snyk_report
          snyk code test --json > .snyk_report/snyk_code.json
          snyk test --json > .snyk_report/snyk_dependencies.json
          python3 .github/workflows/scripts/create_snyk_svg.py
      - name: Publish Snyk report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .snyk_report/
